name: checkin
on:
  schedule:
  - cron:  '45 02 * * *'
  workflow_dispatch:
jobs:
  sync_with_upstream:
    runs-on: ubuntu-latest
    name: auto checkin for traffic

    steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
        ref: master

    - name: checkin
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        architecture: 'x64'
    - run: python ./AutoCheck.py

    - name: timestamp
      run: date
