name: checkin
on:
  schedule:
  - cron:  '45 02 * * *'
  workflow_dispatch:
jobs:
   build:
    runs-on: ubuntu-latest
    name: auto checkin
    
    steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
        ref: main
        
    - name: checkin
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requests==2.26.0
        
    - name: Random sleep
      if: github.event_name == 'schedule'
      run: sleep $(shuf -i 10-300 -n 1)





    - name: Run sign
      run: python ./autocheck.py
